<?php

require_once "modules/rentFunnel/classes/MachinesObjectModel.php";

class rentFunnelChooseMachineModuleFrontController extends ModuleFrontController
{
    public function initContent()
    {
        $machines = $this->getMachines();

        parent::initContent(); // TODO: Change the autogenerated stub

        $this->context->smarty->assign([
            'machines' => $machines,
            'page_title' => 'Choisissez une machine.',
            'shop_url' => $this->context->shop->getBaseURL(),
        ]);

        $this->setTemplate('module:rentFunnel/views/templates/front/chooseMachine.tpl');
    }

    private function getMachines()
    {
        return MachinesObjectModel::getMachines();
    }
}