<?php

class rentFunnel extends Module
{
    public const HOOKS = [
        'displayProductListFunctionalButtons',
        'displayProductActions',
    ];

    public function __construct()
    {
        $this->name = 'rentFunnel';
        $this->version = '1.0.0';
        $this->description = $this->trans('Handles the process by which customers can order coffee when renting a machine.'
            , []
            , 'Module.rentFunnel.Admin');
        $this->author = 'Mathéo BERTIN';

        parent::__construct();

        $this->ps_versions_compliancy = [
            'min' => '1.6',
            'max' => _PS_VERSION_,
        ];
    }

    public function install()
    {
        return parent::install()
            && $this->registerHook(static::HOOKS); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }

    public function hookDisplayProductListFunctionalButtons()
    {
        return $this->display(__FILE__, 'rentFunnel_functional_buttons.tpl');
    }

    public function hookDisplayProductActions()
    {
        return $this->display(__FILE__, 'rentFunnel_product_actions.tpl');
    }
}